CREATE DATABASE readme
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8_general_ci;

USE readme;

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
email VARCHAR(128) NOT NULL UNIQUE,
login VARCHAR(128) NOT NULL UNIQUE,
password VARCHAR(128) NOT NULL,
avatar VARCHAR(128) NOT NULL
);

CREATE TABLE posts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  post_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(128) NOT NULL,
  content_text VARCHAR(512) NULL,
  quote_author VARCHAR(128) NULL,
  img VARCHAR(128) NULL,
  video VARCHAR(128) NULL,
  link VARCHAR(256) NULL,
  views INT UNSIGNED NULL,

  user_id INT UNSIGNED NOT NULL,
  type_id INT UNSIGNED  NOT NULL,
  original_author_id INT UNSIGNED NULL,
  original_id INT UNSIGNED NULL
);

CREATE TABLE comments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  comment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(512) NOT NULL,

  user_id INT UNSIGNED NOT NULL,
  post_id INT UNSIGNED NOT NULL
);

CREATE TABLE likes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  like_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  user_id INT UNSIGNED  NOT NULL,
  post_id INT UNSIGNED  NOT NULL
);

CREATE TABLE subscriptions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

  user_id INT UNSIGNED NOT NULL,
  userto_id INT UNSIGNED NOT NULL
);

CREATE TABLE interlocutors
(
	id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	sender_id INT(10) NOT NULL,
	receiver_id INT(10) NOT NULL,
	last_message_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  message_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  content VARCHAR(512) NOT NULL,

  user_id INT UNSIGNED NOT NULL,
  userto_id INT UNSIGNED NOT NULL
);

CREATE TABLE hashtags (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(128) NOT NULL
);

CREATE TABLE hashtags_posts (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
tag_id INT UNSIGNED NOT NULL,
post_id INT UNSIGNED NOT NULL
);

CREATE TABLE content_type (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
type_name VARCHAR(128) NOT NULL,
icon_type VARCHAR(128) NOT NULL
);

CREATE INDEX c_login ON users(login);
CREATE INDEX c_title ON posts(title);
CREATE FULLTEXT INDEX for_search ON posts(title, content_text, quote_author);
